import { useScroll , motion, useSpring, useTransform } from 'framer-motion'
import React from 'react'

const ScrollAnimation = () => {
    const {scrollYProgress} = useScroll();
    const scaleX = useSpring(scrollYProgress);
   const background =  useTransform(scrollYProgress,
    [0  , 1],
    ["red" , "green"]
   )
  return (
    <div>
     <motion.div 
     style={{transformOrigin : "left",
        scaleX : scaleX,
        backgroundColor : background,
        position : "sticky",
        top : 0,
        width : "100%",
        height :"10px"
     }}
     />
        <div style={{
            maxWidth :"700px",
            margin : "auto",
            padding : "1.2rem"
        }}>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam ut officiis id quas doloremque maiores repellat sequi ipsa animi expedita, natus obcaecati dolorem dolore, saepe eius atque minus earum magni nulla, neque vitae voluptatibus tempora quo similique. Excepturi porro commodi officia quidem consequuntur? Libero reiciendis sit commodi ipsam ab, optio amet itaque expedita placeat, provident velit asperiores. Officiis molestiae temporibus quae consequuntur dolor non totam ipsam aliquam, odio quis provident voluptates beatae reprehenderit odit! Odit incidunt, tenetur autem ullam vel veritatis error tempora nihil eaque iste. Debitis, numquam! Velit provident iusto asperiores. Alias id sunt consequatur rerum cum iure corrupti dolorum nobis! Illo natus distinctio aut excepturi sequi consequuntur soluta cum explicabo dignissimos adipisci? Obcaecati, sunt. Dignissimos ipsam, fugiat dolorem a cupiditate corrupti iure necessitatibus, commodi saepe magnam laborum quisquam quam ipsum facere possimus? Repellat natus dolorum, nobis id magni expedita odio consectetur incidunt! Impedit nihil sit tempora quod nostrum?</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam ut officiis id quas doloremque maiores repellat sequi ipsa animi expedita, natus obcaecati dolorem dolore, saepe eius atque minus earum magni nulla, neque vitae voluptatibus tempora quo similique. Excepturi porro commodi officia quidem consequuntur? Libero reiciendis sit commodi ipsam ab, optio amet itaque expedita placeat, provident velit asperiores. Officiis molestiae temporibus quae consequuntur dolor non totam ipsam aliquam, odio quis provident voluptates beatae reprehenderit odit! Odit incidunt, tenetur autem ullam vel veritatis error tempora nihil eaque iste. Debitis, numquam! Velit provident iusto asperiores. Alias id sunt consequatur rerum cum iure corrupti dolorum nobis! Illo natus distinctio aut excepturi sequi consequuntur soluta cum explicabo dignissimos adipisci? Obcaecati, sunt. Dignissimos ipsam, fugiat dolorem a cupiditate corrupti iure necessitatibus, commodi saepe magnam laborum quisquam quam ipsum facere possimus? Repellat natus dolorum, nobis id magni expedita odio consectetur incidunt! Impedit nihil sit tempora quod nostrum?</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam ut officiis id quas doloremque maiores repellat sequi ipsa animi expedita, natus obcaecati dolorem dolore, saepe eius atque minus earum magni nulla, neque vitae voluptatibus tempora quo similique. Excepturi porro commodi officia quidem consequuntur? Libero reiciendis sit commodi ipsam ab, optio amet itaque expedita placeat, provident velit asperiores. Officiis molestiae temporibus quae consequuntur dolor non totam ipsam aliquam, odio quis provident voluptates beatae reprehenderit odit! Odit incidunt, tenetur autem ullam vel veritatis error tempora nihil eaque iste. Debitis, numquam! Velit provident iusto asperiores. Alias id sunt consequatur rerum cum iure corrupti dolorum nobis! Illo natus distinctio aut excepturi sequi consequuntur soluta cum explicabo dignissimos adipisci? Obcaecati, sunt. Dignissimos ipsam, fugiat dolorem a cupiditate corrupti iure necessitatibus, commodi saepe magnam laborum quisquam quam ipsum facere possimus? Repellat natus dolorum, nobis id magni expedita odio consectetur incidunt! Impedit nihil sit tempora quod nostrum?</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam ut officiis id quas doloremque maiores repellat sequi ipsa animi expedita, natus obcaecati dolorem dolore, saepe eius atque minus earum magni nulla, neque vitae voluptatibus tempora quo similique. Excepturi porro commodi officia quidem consequuntur? Libero reiciendis sit commodi ipsam ab, optio amet itaque expedita placeat, provident velit asperiores. Officiis molestiae temporibus quae consequuntur dolor non totam ipsam aliquam, odio quis provident voluptates beatae reprehenderit odit! Odit incidunt, tenetur autem ullam vel veritatis error tempora nihil eaque iste. Debitis, numquam! Velit provident iusto asperiores. Alias id sunt consequatur rerum cum iure corrupti dolorum nobis! Illo natus distinctio aut excepturi sequi consequuntur soluta cum explicabo dignissimos adipisci? Obcaecati, sunt. Dignissimos ipsam, fugiat dolorem a cupiditate corrupti iure necessitatibus, commodi saepe magnam laborum quisquam quam ipsum facere possimus? Repellat natus dolorum, nobis id magni expedita odio consectetur incidunt! Impedit nihil sit tempora quod nostrum?</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam ut officiis id quas doloremque maiores repellat sequi ipsa animi expedita, natus obcaecati dolorem dolore, saepe eius atque minus earum magni nulla, neque vitae voluptatibus tempora quo similique. Excepturi porro commodi officia quidem consequuntur? Libero reiciendis sit commodi ipsam ab, optio amet itaque expedita placeat, provident velit asperiores. Officiis molestiae temporibus quae consequuntur dolor non totam ipsam aliquam, odio quis provident voluptates beatae reprehenderit odit! Odit incidunt, tenetur autem ullam vel veritatis error tempora nihil eaque iste. Debitis, numquam! Velit provident iusto asperiores. Alias id sunt consequatur rerum cum iure corrupti dolorum nobis! Illo natus distinctio aut excepturi sequi consequuntur soluta cum explicabo dignissimos adipisci? Obcaecati, sunt. Dignissimos ipsam, fugiat dolorem a cupiditate corrupti iure necessitatibus, commodi saepe magnam laborum quisquam quam ipsum facere possimus? Repellat natus dolorum, nobis id magni expedita odio consectetur incidunt! Impedit nihil sit tempora quod nostrum?</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam ut officiis id quas doloremque maiores repellat sequi ipsa animi expedita, natus obcaecati dolorem dolore, saepe eius atque minus earum magni nulla, neque vitae voluptatibus tempora quo similique. Excepturi porro commodi officia quidem consequuntur? Libero reiciendis sit commodi ipsam ab, optio amet itaque expedita placeat, provident velit asperiores. Officiis molestiae temporibus quae consequuntur dolor non totam ipsam aliquam, odio quis provident voluptates beatae reprehenderit odit! Odit incidunt, tenetur autem ullam vel veritatis error tempora nihil eaque iste. Debitis, numquam! Velit provident iusto asperiores. Alias id sunt consequatur rerum cum iure corrupti dolorum nobis! Illo natus distinctio aut excepturi sequi consequuntur soluta cum explicabo dignissimos adipisci? Obcaecati, sunt. Dignissimos ipsam, fugiat dolorem a cupiditate corrupti iure necessitatibus, commodi saepe magnam laborum quisquam quam ipsum facere possimus? Repellat natus dolorum, nobis id magni expedita odio consectetur incidunt! Impedit nihil sit tempora quod nostrum?</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam ut officiis id quas doloremque maiores repellat sequi ipsa animi expedita, natus obcaecati dolorem dolore, saepe eius atque minus earum magni nulla, neque vitae voluptatibus tempora quo similique. Excepturi porro commodi officia quidem consequuntur? Libero reiciendis sit commodi ipsam ab, optio amet itaque expedita placeat, provident velit asperiores. Officiis molestiae temporibus quae consequuntur dolor non totam ipsam aliquam, odio quis provident voluptates beatae reprehenderit odit! Odit incidunt, tenetur autem ullam vel veritatis error tempora nihil eaque iste. Debitis, numquam! Velit provident iusto asperiores. Alias id sunt consequatur rerum cum iure corrupti dolorum nobis! Illo natus distinctio aut excepturi sequi consequuntur soluta cum explicabo dignissimos adipisci? Obcaecati, sunt. Dignissimos ipsam, fugiat dolorem a cupiditate corrupti iure necessitatibus, commodi saepe magnam laborum quisquam quam ipsum facere possimus? Repellat natus dolorum, nobis id magni expedita odio consectetur incidunt! Impedit nihil sit tempora quod nostrum?</p>
        </div>
      
    </div>
  )
}

export default ScrollAnimation
